"""Created Puppy and Owner Tables

Revision ID: 5c6698766bb6
Revises: 
Create Date: 2022-03-03 15:12:16.806658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c6698766bb6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pups', sa.Column('age', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pups', 'age')
    # ### end Alembic commands ###
